

SELECT * FROM USER_INDEXES;


SELECT ROWID,DEPTNO, DNAME,LOC
FROM DEPT;


SELECT ID,NAME, 

SELECT * FROM user_indexes;

--인덱스 리빌드
ALTER INDEX PK_EMP REBUILD;

SELECT * 
FROM USER_IND_COLUMNS;

CREATE TABLE ZIPCODE1 AS (SELECT * FROM ZIPCODE);

--ZIPCODE 테이블에 SEQ컬럼을 UNIQUE 인덱스로 설정
CREATE INDEX IND_ZIPCODE ON ZIPCODE (SEQ);

SELECT * 
FROM USER_INDEXES;

SELECT * 
FROM USER_IND_COLUMNS
WHERE TABLE_NAME='ZIPCODE';


--ZIPCODE 테이블에서 SEQ가 50000~51000 사이의 레코드를 조회

SELECT ZIPCODE, SIDO ,GUGUN, DONG ,BUNJI,SEQ
FROM ZIPCODE
WHERE SEQ BETWEEN 50000 AND 51000;

--ZIPCODE1 테이블에서 SEQ가 50000~51000 사이의 레코드를 조회
SELECT ZIPCODE, SIDO ,GUGUN, DONG ,BUNJI,SEQ
FROM ZIPCODE1
WHERE SEQ BETWEEN 50000 AND 51000;


-----인덱스를 사용한 정렬-------
--EMP 테이블은 EMPNO가 PK로 오름차순 인덱스로 생성되어있다.

--사원테이블에서 연봉이 1500~3000사이인
-- 사원번호 ,사원명, 연봉, 입사일 조회
-- 단 연봉의 오름차순으로 정렬하여 조회
CREATE INDEX IND_EMP ON EMP(SAL DESC);
DROP INDEX IND_EMP;

SELECT *
FROM USER_INDEXES
WHERE TABLE_NAME = 'EMP';

SELECT EMPNO, ENAME, SAL, HIREDATE
FROM EMP 
WHERE SAL BETWEEN 1500 AND 3000;
