--하나의 테이블 사용
--emp 테이블에서 7788사원이 존재한다면 직무가 'MANAGER'인 사원들을 검색


SELECT EMPNO, ENAME, JOB, SAL
FROM EMP
WHERE JOB = 'MANAGER'
AND EXISTS
(SELECT 1 FROM EMP WHERE EMPNO = 7788); --조회 컬럼이 있냐?


--CP_EMP1 테이블과 EMP 테이블에 동일하게 존재하는 사원에 대해서
--사원번호, 사원명 , 부서번호 , 입사일, 연봉을 검색하세요
--EXISTS에 들어가는 SUBQUERY에 조건에 두 테이블의 사원 번호를 비교해야한다.

SELECT EMPNO, ENAME,DEPTNO,HIREDATE,SAL
FROM EMP
WHERE DEPTNO=20 AND EXISTS (SELECT 1 FROM CP_EMP1 WHERE CP_EMP1.EMPNO = EMP.EMPNO);

SELECT *
FROM EMP;

SELECT *
FROM CP_EMP1;

--CAR_MODEL 테이블과 CAR_MAKER 테이블에서 동일 모델이
-- 존재하는 경우 모델명 K5인 차량에 대해서 모델명, 년식 ,가격 옵션을 조회

SELECT MODEL, CAR_YEAR , PRICE , CAR_OPTION 
FROM CAR_MODEL 
WHERE MODEL ='K5' AND EXISTS (SELECT 1 FROM CAR_MAKER WHERE CAR_MAKER.MODEL =CAR_MODEL.MODEL);

SELECT *
FROM CAR_MODEL ;

--------------ALTER를 사용한 테이블 변경------------
CREATE TABLE TEST_ALTER (
	NUM  NUMBER,
	NEAM VARCHAR2(20),
	ADDR NUMBER
);

--컬럼명 변경
ALTER TABLE TEST_ALTER RENAME COLUMN NEAM TO NAME;

--데이터형 변경
--레코드가 없는 경우 : 데이터형 자체를 변경할 수 있다.
ALTER TABLE TEST_ALTER MODIFY ADDR VARCHAR2(300); 

INSERT INTO TEST_ALTER( NUM, NAME, ADDR ) VALUES (1,'김선경','서울시 강남구');

SELECT *
FROM TEST_ALTER ;
--레코드가 있는 경우 : 동일 데이터형에서 크기만 변경할 수 있다.
ALTER TABLE TEST_ALTER MODIFY ADDR NUMBER(22);

ALTER TABLE TEST_ALTER MODIFY ADDR VARCHAR2(300) NOT NULL; 

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME= 'TEST_ALTER';

--컬럼추가
--TEST_ALTER 테이블에 AGE컬럼 추가
ALTER TABLE TEST_ALTER ADD AGE NUMBER(3) CHECK (AGE BETWEEN 20 AND 29);

--TEST_ALTER 테이블에 PRIMARY KEY 제약을 가지는 ID 컬럼을 추가.
--모든 레코드 절사
TRUNCATE TABLE TEST_ALTER;

ALTER TABLE TEST_ALTER  ADD ID CHAR(20) CONSTRAINT PK_TEST_ALTER_ID PRIMARY KEY;

INSERT INTO TEST_ALTER( NUM, NAME, ADDR,AGE,ID ) VALUES (1,'김선경','서울시 강남구',25,'KIM');
INSERT INTO TEST_ALTER( NUM, NAME, ADDR,AGE,ID ) VALUES (2,'임태균','경기도 용인시 처인구',27,'LEEM');

--컬럼 삭제
ALTER TABLE TEST_ALTER  DROP COLUMN AGE;




--테이블명 변경 
ALTER TABLE TEST_ALTER RENAME TO TEST_ALTER1;

--제약사항 추가, 삭제

-- 제약사항 PK 삭제
ALTER TABLE TEST_ALTER1 DROP CONSTRAINT PK_TEST_ALTER_ID;
-- 체크 조건 삭제하기
ALTER TABLE TEST_ALTER1 DROP CONSTRAINT SYS_C007563;
--제약사항이 삭제 되었으므로 제약사항에 위배되는 레코드를 추가할 수 있다.
INSERT INTO TEST_ALTER1 (ID) VALUES ('KIM');

--제약사항 추가: 레코드의 상황에 따라 다르다
--ID 컬럼에 PK 제약 설정
ALTER TABLE TEST_ALTER1 ADD CONSTRAINT PK_TEST_ALTER1_ID PRIMARY KEY(ID);

ALTER TABLE TEST_ALTER1 DISABLE CONSTRAINT PK_TEST_ALTER1_ID;

ALTER TABLE TEST_ALTER1 ENABLE CONSTRAINT PK_TEST_ALTER1_ID;
SELECT *
FROM TEST_ALTER1 ;

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME= 'TEST_ALTER1';

DELETE 
FROM TEST_ALTER1 
WHERE NUM IS NULL;