

SELECT *
FROM EMP;

SELECT EMPNO, ENAME, HIREDATE, SAL
FROM EMP
WHERE SAL > (SELECT  SAL 
FROM EMP
WHERE ENAME= 'SCOTT');
--SELF 조인은 조회용도 테이블과 조건용도 테이블을 구분하여 사용한다.
SELECT E.EMPNO, E.ENAME ,E.HIREDATE , E.SAL 
FROM EMP E, EMP E1 
WHERE (E.SAL > E1.SAL) AND (E1.ENAME='SCOTT');


SELECT *
FROM user_sequences;

--1~99999까지 1씩 증가하는 시퀀스 생성
CREATE SEQUENCE TEST_SEQ
START WITH 1
MAXVALUE 99999
INCREMENT BY 1;

--CURRVAL 현재번호 : 시퀀스를 메모리에 올리는 일은 할 수 없다.
SELECT TEST_SEQ.CURRVAL
FROM DUAL;

--NEXTVAL : 다음 번호 : 시퀀스가 메모리에 존재하지 않으면 
--메모리에 올리고, 다음 번호를 얻을 수 있다.

SELECT TEST_SEQ.NEXTVAL
FROM DUAL;


DROP SEQUENCE TEST_SEQ;

SELECT *
FROM USER_SEQUENCES;

CREATE SEQUENCE TEST_SEQ
START WITH 10 -->LAST NUMBER를 바꾼 것.
MAXVALUE 9999990
INCREMENT BY 10
CACHE 100 
CYCLE;

SELECT TEST_SEQ.NEXTVAL
FROM DUAL;

--INSERT 할 때 주로 사용
CREATE TABLE USE_SEQUENCE(
NUM NUMBER,
NAME VARCHAR2(30),
CONSTRAINT PK_USE_SEQUENCE PRIMARY KEY (NUM)
);
-- INSERT 할 때 사용하는 SEQUENCE 생성
CREATE SEQUENCE USE_SEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999
CYCLE;

--SEQUENCE를 사용한 INSERT 
--시퀀스는 INSERT문에서 ORACLE 11G 부터 SELECT 없이 바로 사용할 수 있다.
INSERT INTO USE_SEQUENCE(NUM,NAME) VALUES (USE_SEQ.NEXTVAL, '강다연');

INSERT INTO USE_SEQUENCE(NUM,NAME) VALUES (USE_SEQ.NEXTVAL, '김다영');
INSERT INTO USE_SEQUENCE(NUM,NAME) VALUES (USE_SEQ.NEXTVAL, '김인영');
SELECT * FROM USE_SEQUENCE;


CREATE TABLE USE_SEQ2 (
NUM CHAR(8),
NAME VARCHAR2(30),
CONSTRAINT PK_USE_SEQUENCE2 PRIMARY KEY (NUM)
);

ALTER TABLE USE_SEQ2 RENAME TO USE_SEQUENCE2;

--USE_SEQUENCE2 테이블에 아래와 같은 형태의 증가하는 문자열을 추가
--증가하는 수 : USE_SEQ 시퀀스를 사용.
--번호 : S_000001 , 이름 :  김주민 다음번호 박상준, 다음 번호 박서현
INSERT INTO USE_SEQUENCE2 (NUM,NAME)VALUES('S_'||LPAD(USE_SEQ.NEXTVAL,6,0),'김주민');
INSERT INTO USE_SEQUENCE2 (NUM,NAME)VALUES(CONCAT('S_',LPAD(USE_SEQ.NEXTVAL,6,0)),'박상준');
INSERT INTO USE_SEQUENCE2 (NUM,NAME)VALUES(CONCAT('S_',LPAD(USE_SEQ.NEXTVAL,6,0)),'박서현');
SELECT * FROM USE_SEQUENCE2 ;

