

--VIEW 생성

--단순 VIEW

GRANT CREATE VIEW TO SCOTT;

SELECT *
FROM DBA_USERS;


CREATE VIEW EMP_VIEW(EMPNO,ENAME,DEPTNO,HIREDATE,SAL)
AS (SELECT * FROM CP_EMP1 WHERE DEPTNO IN (10,30));

--VIEW 검색
SELECT * 
FROM USER_VIEWS;

SELECT EMPNO, ENAME , DEPTNO, TO_CHAR(HIREDATE, 'YYYY-MM-DD') HIREDATE, SAL
FROM EMP_VIEW
WHERE DEPTNO=10;



--VIEW를 사용하면 WHERE절을 정의하지 않더라도 10,30번 부서 사원만 볼 수 있다.
SELECT * 
FROM EMP_VIEW;

--DML가능 : 실제 테이블에 반영된다.

INSERT INTO EMP_VIEW (EMPNO,ENAME, DEPTNO, HIREDATE, SAL)
VALUES (1114,'홍지성',10,SYSDATE,3200);

SELECT *
FROM CP_EMP1;

UPDATE EMP_VIEW 
SET SAL=3000
WHERE EMPNO=1114;

DELETE FROM EMP_VIEW WHERE EMPNO=1114;


--READ ONLY : 

CREATE OR REPLACE VIEW EMP2 AS 
(SELECT * FROM CP_EMP2 WHERE DEPTNO=30)
WITH  READ ONLY;

SELECT *
FROM USER_VIEWS;

SELECT *
FROM EMP2;
--WITH READ ONLY는 DML(INSERT,UPDATE,DELETE)이 되지 않는다.
INSERT INTO EMP2 (EMPNO,ENAME, JOB,DEPTNO,HIREDATE,SAL)
VALUES(1111,'김성견','프로',10,SYSDATE,3500);

CREATE TABLE CP_DEPT AS (SELECT * FROM DEPT);
CREATE TABLE CP_EMP AS (SELECT *FROM EMP)
----CP_DEPT와 CP_EMP를 사용한 복합뷰 생성
--복합뷰 생성

CREATE OR REPLACE VIEW JOIN_VIEWS AS(
SELECT D.DEPTNO, D.DNAME, D.LOC, E.EMPNO, E.ENAME, E.SAL, E.HIREDATE
FROM DEPT D, EMP E
WHERE (E.DEPTNO=D.DEPTNO)
);

SELECT * FROM JOIN_VIEWS
WHERE DEPTNO= 10;

INSERT INTO JOIN_VIEW(DEPTNO,DNAME,LOC,EMPNO,ENAME,JOB,SAL,HIREDATE)
VALUES (10,'개발부','서울',1111,'김선경','')














