
--여러개의 컬럼이 하나의 pk로 구성.
CREATE TABLE PRIMARY_multi(
	id varchar2(20),
	num NUMBER(6),
	name varchar2(30),
	hiredate DATE,
	CONSTRAINT pk_primary_multi PRIMARY key(id,num)
);
DROP TABLE PRIMARY_multi;

SELECT *
FROM USER_constraints
WHERE table_name = 'PRIMARY_MULTI';

SELECT *
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME='PRIMARY_MULTI';

---------추가성공-------
--최초입력
INSERT INTO PRIMARY_MULTI (ID,NUM,NAME,HIREDATE) VALUES('kim',1,'김주민',SYSDATE);


--모든 PK컬럼에 다른 값이 들어가는 경우
INSERT INTO PRIMARY_MULTI (ID,NUM,NAME,HIREDATE) VALUES('kim',2,'김주민',SYSDATE);
INSERT INTO PRIMARY_MULTI (ID,NUM,NAME,HIREDATE) VALUES('park',2,'김주민',SYSDATE);
-----------------추가 실패---------
--이전 레코드와 동일한 값이 입력되는 경우
INSERT INTO PRIMARY_MULTI (ID,NUM,NAME,HIREDATE) VALUES('kim',1,'홍찬영',SYSDATE+1);

--NULL이 입력되는 경우
--id에 null이 입력 => 컬럼명을 생략
INSERT INTO PRIMARY_MULTI (NAME,HIREDATE) VALUES('홍찬영',SYSDATE+1);

--num에 null이 입력 => 컬럼명 생략
INSERT INTO PRIMARY_MULTI (id,NAME,HIREDATE) VALUES('hong','홍찬영',SYSDATE+1);

INSERT INTO PRIMARY_MULTI (ID,NUM,NAME,HIREDATE) VALUES('',0,'홍찬영',SYSDATE+1);
SELECT *
FROM PRIMARY_MULTI ;

---foreign key----
--자식 테이블의 컬럼명은 부모테이블의 컬럼명과 같을 필요는 없으나 대부분 같게 설정한다.
--데이터형은 반드시 같아야 한다.
--컬럼단위 제약


CREATE TABLE FOREIGN_CLUMN(
 ID VARCHAR2(20) CONSTRAINT FK_FOREIGN_COLUMN_ID REFERENCES PRIMARY_COLUMN(ID),
 AGE NUMBER(3)
);
--추가 성공
--부모 테이블의 PK컬럼 값으로만 추가 될 때
SELECT ID,NAME,ADDR
FROM PRIMARY_COLUMN ;

INSERT INTO FOREIGN_CLUMN(ID,AGE) VALUES('kim',20);
INSERT INTO FOREIGN_CLUMN(ID,AGE) VALUES('kim',21);
INSERT INTO FOREIGN_CLUMN(ID,AGE) VALUES('kim',22);
INSERT INTO FOREIGN_CLUMN(ID,AGE) VALUES('park',22);
--NULL이 입력될 때
INSERT INTO FOREIGN_CLUMN (ID,AGE)VALUES('',22);
--컬럼생략
INSERT INTO FOREIGN_CLUMN (AGE)VALUES(32);
--추가 실패
--부모테이블에 존재하지 않는 값으로 레코드를 추가할 때
INSERT INTO FOREIGN_CLUMN(ID,AGE) VALUES('hong',20);


--테이블 단위 제약사항
CREATE TABLE FOREIGN_TABLE ( 
	R_ID VARCHAR2(20),
	AGE NUMBER(3),
	CONSTRAINT FK_FOREIGN_TABLE_R_ID FOREIGN KEY(R_ID) REFERENCES PRIMARY_TABLE(ID)
);

SELECT * 
FROM USER_CONSTRAINTS 
WHERE CONSTRAINT_TYPE = 'R';


--일반컬럼은 FOREIGN KEY로 참조할 수 없다.


CREATE TABLE CP_EMP_FK_TEST(
	EMPNO NUMBER(4) CONSTRAINT FK_CP_EMP_EMPNO REFERENCES CP_EMP1(EMPNO),
	ZIPCODE CHAR(7)
);


SELECT *  
FROM FOREIGN_CLUMN ;