--UNION : 중복데이터를 보여주지 않는다.
--UNION ALL : 중복데이터를 보여준다.
--CP_EMP1에서 모든 사원의 이름을 소문자로 변경한다.
UPDATE CP_EMP1 
SET  ENAME= LOWER(ENAME);

UPDATE CP_EMP1 
SET  ENAME= UPPER(ENAME)
WHERE EMPNO IN (7698,7521,7788,7900,7902);


--EMP : 본사, CP_EMP : 지사
--모든 본사사원과 지사사원을 조회
--조회 컬럼 : 사원번호 , 사원명 ,부서번호, 입사일, 연봉
SELECT EMPNO, ENAME, DEPTNO, HIREDATE, SAL
FROM EMP
UNION ALL
SELECT EMPNO, ENAME, DEPTNO, HIREDATE, SAL 
FROM CP_EMP1;

SELECT EMPNO, ENAME, DEPTNO, HIREDATE, SAL
FROM EMP
UNION
SELECT EMPNO, ENAME, DEPTNO, HIREDATE, SAL 
FROM CP_EMP1;

--에러
--컬럼의 수가 맞지 않는 경우 . 
SELECT EMPNO, ENAME, DEPTNO, HIREDATE, SAL
FROM EMP
UNION ALL
SELECT EMPNO, ENAME, DEPTNO, HIREDATE
FROM CP_EMP1;
--컬럼의 데이터형이 맞지 않는 경우 
SELECT EMPNO, ENAME
FROM EMP
UNION ALL
SELECT ENAME, EMPNO 
FROM CP_EMP1;

--컬럼명이 다른 경우에는 에러가 발생하지 않는다.

SELECT EMPNO,ENAME,JOB ,DEPTNO, HIREDATE, SAL
FROM CP_EMP2
UNION ALL

SELECT DEPTNO,JOB ,ENAME,EMPNO , HIREDATE, SAL
FROM EMP;

SELECT TNAME
FROM TAB;

--우편번호 테이블에서 동이름이 '마계동'인 우편번호 시도 구군 동  번지를 조회하고
--접속 계정이 생성한 테이블명을 함께 조회

SELECT ZIPCODE , SIDO, GUGUN ,DONG ,BUNJI 
FROM ZIPCODE 
WHERE DONG LIKE '%마계동%'
UNION ALL
SELECT TNAME,'0','0','0','0'
FROM TAB;

SELECT EMPNO,ENAME, DEPTNO, HIREDATE, SAL
FROM CP_EMP1;