

--숙제.
--1. 배기량이 1500~3000 사이인 차량의 제조국,제조사,모델명,년식,가격,
--    이미지,입력일,배기량, 옵션을 조회
--   단. 출력은 배기량의 내림차순 정렬했을때 3~6번째 레코드만 조회하고,
--     옵션은 처음 ',' 까지만 출력 할것. 가격과 연식은 3자리마다 ,를 넣어출력,
 --    입력일은 월-일-년 의 형식으로 출력 할것.

SELECT NUM , COUNTRY, MAKER, MODEL, TO_CHAR(CAR_YEAR,'9,999')CAR_YEAR
,TO_CHAR (PRICE,'9,999')PRICE,CAR_IMG,TO_DATE(HIREDATE,'MM-DD-YYYY') HIREDATE
,CC,SUBSTR( CAR_OPTION, 1,INSTR(CAR_OPTION,',',1,1)-1) CAR_OPTION
FROM(SELECT ROW_NUMBER () OVER (ORDER BY CC DESC) NUM , COUNTRY, 
MAKER, MODEL, CAR_YEAR,PRICE,CC,CAR_IMG,HIREDATE,CAR_OPTION
FROM(SELECT CC.COUNTRY , CMA.MAKER , CMO.MODEL,
CMO.CAR_YEAR ,CMO.PRICE ,CMO.CAR_IMG ,CMO.HIREDATE,
CMO.CC, CMO.CAR_OPTION 
FROM CAR_COUNTRY  CC
INNER JOIN   CAR_MAKER  CMA 
ON CMA.MAKER = CC.MAKER
INNER JOIN CAR_MODEL CMO
ON CMA.MODEL = CMO.MODEL)
WHERE CC BETWEEN 1500 AND 3000)
WHERE NUM BETWEEN 3 AND 6;

SELECT COUNTRY, MAKER, MODEL, CAR_YEAR, CAR_IMG, CC, HIREDATE
FROM (SELECT  CC.COUNTRY ,CC.MAKER ,CMA.MODEL ,CMO.CAR_YEAR 
,CMO.PRICE ,CMO.CC, CMO.HIREDATE ,CMO.CAR_IMG ,CMO.CAR_OPTION,
ROW_NUMBER () OVER(ORDER BY CC DESC) NUM 
FROM CAR_COUNTRY CC, CAR_MAKER CMA, CAR_MODEL CMO
WHERE (CMA.MAKER =CC.MAKER AND CMO.MODEL =CMA.MODEL)AND(CMO.CC BETWEEN 1500 AND 3000))
WHERE NUM BETWEEN 3 AND 6;
--부서번호가 10, 30,40번인 모든 부서의 사원번호,사원명,입사일,
-- 연봉,연봉순위,부서명,부서번호,위치, 우편번호,시도, 구군,동,번지 를 조회.
-- 단,출력은 사원번호의 오름차순으로 정렬했을 때 2~5번째 레코드만 출력,
--   우편번호는 '-' 뒤부터 끝까지 출력, 번지가 없다면 '번지없음'으로 대체
--  하여 출력 ,입사일은 월-일-년 요일까지 출력  ( emp 사원번호와 zipcode SEQ컬럼을 조인조건 사용)

SELECT NUM,EMPNO,ENAME, TO_CHAR(HIREDATE,'MM-DD-YYYY DAY'), SAL, SAL_RANK, DNAME, DEPTNO,LOC,SUBSTR(ZIPCODE,4) ZIPCODE , SIDO, GUGUN, DONG, NVL(BUNJI,'번지 없음')
FROM(SELECT ROW_NUMBER() OVER(ORDER BY EMPNO) NUM,DNAME, LOC ,EMPNO,SAL_RANK, ENAME, HIREDATE, SAL, JOB, DEPTNO, ZIPCODE, SIDO, GUGUN, DONG , BUNJI
FROM (SELECT E.EMPNO , E.ENAME ,ROW_NUMBER()OVER(ORDER BY SAL DESC) SAL_RANK,D.DNAME ,D.LOC  , E.HIREDATE ,E.SAL ,E.JOB ,D.DEPTNO, Z.ZIPCODE ,Z.SIDO ,Z.GUGUN ,Z.DONG ,Z.BUNJI  
FROM EMP E
INNER JOIN ZIPCODE Z
ON (Z.SEQ = E.EMPNO)
RIGHT OUTER JOIN DEPT D	
ON (E.DEPTNO=D.DEPTNO)
WHERE D.DEPTNO IN (10,30,40)))
WHERE NUM BETWEEN 2 AND 5 ;



SELECT EMPNO, ENAME, HIREDATE, SAL, SAL_RANK, DNAME, DEPTNO, LOC, ZIPCODE, SIDO , GUGUN ,DONG ,BUNJI
	,EMPNO_ASC
FROM 
(SELECT EMPNO, ENAME, SAL, SAL_RANK, DNAME,HIREDATE, DEPTNO, LOC, ZIPCODE, SIDO ,GUGUN, DONG ,BUNJI,
	ROW_NUMBER() OVER(ORDER BY EMPNO) EMPNO_ASC
FROM
(SELECT E.EMPNO ,E.ENAME, E.HIREDATE ,E.SAL, ROW_NUMBER() OVER(ORDER BY SAL DESC) SAL_RANK
	,D.DNAME, D.DEPTNO, D.LOC, Z.ZIPCODE , Z.SIDO ,Z.GUGUN ,Z.DONG ,Z.BUNJI 
FROM DEPT D, EMP E ,ZIPCODE Z
WHERE (E.DEPTNO(+)=D.DEPTNO AND Z.SEQ(+)=E.EMPNO) AND (D.DEPTNO IN (10,30,40))))
WHERE EMPNO_ASC BETWEEN 2 AND 5;

--3. 차량의 제조사가 '현대','기아','삼성','BMW','AUDI'이고 옵션에 'ABS','TCS'가
-- 있는 차량의  제조국, 제조사,모델명, 연식,가격, 옵션, 이미지, 배기량 조회
  --단, 연식의 내림차순 정렬하고, 연식이 같다면 가격의 내림차순으로 정렬
--   하여 출력, 이미지는 이미지명과 확장자를 구분하여 출력할것,
--   제조사명이 영어라면 Bmw, Audi 의 형식으로 출력 . 


SELECT COUNTRY , MAKER, MODEL, CAR_YEAR, PRICE, CAR_OPTION, SUBSTR (CAR_IMG,1, INSTR(CAR_IMG,'.',1,1)-1) IMG ,
SUBSTR(CAR_IMG,INSTR(CAR_IMG,'.',1,1)+1) EXT, CC 
FROM (SELECT CC.COUNTRY ,CMA.MAKER , CMO.MODEL, CMO.CAR_YEAR ,CMO.PRICE ,CMO.CAR_OPTION,
CMO.CAR_IMG ,CMO.CC 
FROM CAR_COUNTRY CC
INNER JOIN CAR_MAKER CMA 
ON CMA.MAKER = CC.MAKER 
INNER JOIN CAR_MODEL  CMO
ON CMA.MODEL = CMO.MODEL 
WHERE (CMA.MAKER IN ('현대','기아','삼성','BMW','AUDI')) AND 
(CMO.CAR_OPTION LIKE '%ABS%'OR CMO.CAR_OPTION LIKE 'TCS'))
ORDER BY CAR_YEAR DESC, PRICE DESC;

--4. 모델명이 'K5','아반테', '소렌토','A8','SM3' 인 차량의 번호, 모델명, 제조국,
--  제조사,가격,연식을 아래와 같은 형식의 문장으로 출력.
--  단,번호는 1번부터 출력하고,
--   출력 가격의 오름차순을 정렬했을 때 2~7 사이의 레코드만 출력,
--   [모델명] 차량의 연식은 [ xxxx ]이고, 제조국은 [국산|수입]이며, 
--   [XX]사가 제조사입니다. 가격은 [0,000,000]원 입니다.
SELECT  NUM-1, '['||MODEL||'] '||' 차량의 연식은 [ '||CAR_YEAR||']이고, 제조국은 ['||COUNTRY||']이며, ['
||MAKER||']사가 제조사입니다. 가격은 ['||TO_CHAR(PRICE,'0,000,000')||']원 입니다.'
FROM (SELECT ROW_NUMBER() OVER (ORDER BY PRICE) NUM,COUNTRY, MAKER, MODEL , CAR_YEAR, PRICE, CC  
FROM(SELECT CC.COUNTRY , CMA.MAKER , CMO.MODEL,
CMO.CAR_YEAR ,CMO.PRICE ,CMO.CC
FROM CAR_COUNTRY  CC
INNER JOIN   CAR_MAKER  CMA 
ON CMA.MAKER = CC.MAKER
INNER JOIN CAR_MODEL CMO
ON CMA.MODEL = CMO.MODEL)
WHERE MODEL IN ('K5','아반테','소렌토','A8','SM3')
)
WHERE NUM BETWEEN 2 AND 7;

--5. 제조사가 '현대'인 차량의 년식, 모델명, 연식별 총가격을 조회하세요.
SELECT CAR_YEAR, MODEL, SUM(PRICE) TOTAL_PRICE
FROM
(SELECT CMO.CAR_YEAR , CMO.MODEL ,CMO.PRICE 
FROM CAR_MAKER CMA
INNER JOIN CAR_MODEL CMO
ON (CMA.MODEL = CMO.MODEL)
WHERE CMA.MAKER  = '현대')
GROUP BY CAR_YEAR,MODEL;

--6. 사원명이 'S'로 끝나거나 이름5자이면서 세번째 글자가 'A'인 
--   사원의  사원번호, 사원명, 입사일,연봉,세금, 실수령액, 연봉인상액,
--   부서번호,부서명,위치,우편번호,시도, 구군,동,번지 를 조회
--   단,실수령액은 연봉+퇴직금+보너스-세금(연봉 3.3) 로 계산
--     연봉인상액은 부서번호에 따라 차등 인상 
--     10- 년봉 7%, 20- 년봉 4%, 30- 년봉+보너스 10%, 그외 3%로 
--     계산하여 3자리마다 ,를 넣어 출력. 
 --    모든 영어는 소문자로 출력.
SELECT EMPNO, LOWER(ENAME) ENAME , HIREDATE, SAL,TAX,
(SAL+COMM-TAX) REAL_SAL,TO_CHAR(DECODE(DEPTNO,10,SAL*0.07,20,SAL*0.04,30,(SAL+COMM)*0.1,SAL*0.3),'0,999')SAL_INC
,DEPTNO, LOWER(DNAME) DNAME, LOWER(LOC) LOC, ZIPCODE, SIDO, GUGUN, DONG, BUNJI
FROM (SELECT E.EMPNO , E.ENAME ,E.HIREDATE ,(E.SAL*0.033) TAX ,E.SAL ,D.DEPTNO ,D.DNAME ,D.LOC,
Z.ZIPCODE ,Z.SIDO ,Z.GUGUN ,Z.DONG ,Z.BUNJI , NVL2(E.COMM,E.COMM,0) COMM
FROM EMP E
INNER JOIN ZIPCODE Z
ON (Z.SEQ = E.EMPNO)
RIGHT OUTER JOIN DEPT D	
ON (E.DEPTNO=D.DEPTNO))
WHERE (ENAME LIKE '%S' OR ENAME LIKE '__A__');


SELECT *
FROM DEPT;

SELECT *
FROM EMP
WHERE ENAME LIKE '__A__';

SELECT *
FROM ZIPCODE;


SELECT *
FROM CAR_MODEL ;

SELECT *
FROM CAR_MAKER;



SELECT NUM, PRICE, CC
FROM(SELECT ROW_NUMBER () OVER( ORDER  BY PRICE )NUM ,PRICE, CC
FROM(SELECT PRICE , MODEL,CC
FROM CAR_MODEL
WHERE MODEL IN ('K5','아반테','소렌토','A8','SM3') 
ORDER BY PRICE , CC))
WHERE NUM BETWEEN 2 AND 7;



SELECT SUBSTR (CAR_IMG,1, INSTR(CAR_IMG,'.',1,1)-1) IMG ,
SUBSTR(CAR_IMG,INSTR(CAR_IMG,'.',1)+1) EXT
FROM CAR_MODEL;


SELECT CAR_YEAR, PRICE
FROM CAR_MODEL 
ORDER BY CAR_YEAR DESC ,PRICE DESC;

SELECT *
FROM EMP;

SELECT *
FROM ZIPCODE;

SELECT *
FROM DEPT;

SELECT TO_CHAR(EMPNO, '9,999') 
FROM EMP;

SELECT *
FROM ZIPCODE;
ON 

SELECT * 
FROM CAR_MODEL;

SELECT *  FROM CAR_MODEL; 
SELECT SUBSTR( CAR_OPTION, 1,INSTR(CAR_OPTION,',',1,1)-1)
FROM CAR_MODEL;

SELECT *
FROM CAR_COUNTRY ;

SELECT * FROM CAR_maker;